

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2011 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: B3-432E-F558-21			    |
; |				Ilfak Guilfanov				    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	47F53C130B7D5269550191DFEAFE8DD7
; Input	CRC32 :	5EBD0A43

; File Name   :	C:\users\benito\Mis Documentos\Documentos\Universidad\IEEE SB UGR\xtreme\minecoders\10_IEEE Xplore\p.com
; Format      :	MS-DOS COM-file
; Base Address:	1000h Range: 10100h-1016Ch Loaded length: 6Ch

		.686p
		.mmx
		.model tiny

; ===========================================================================

; Segment type:	Pure code
seg000		segment	byte public 'CODE' use16
		assume cs:seg000
		org 100h
		assume es:nothing, ss:nothing, ds:seg000, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================


		public start
start		proc near
		mov	di, 400h
		mov	si, 0C0h
		push	si
		xor	cx, cx

loc_10109:				; CODE XREF: start+10j
		mov	ah, 0
		int	16h		; KEYBOARD - READ CHAR FROM BUFFER, WAIT IF EMPTY
					; Return: AH = scan code, AL = character
		cmp	al, 2Eh
		stosb
		loopne	loc_10109
		not	cx
		sub	dx, dx
		mov	bp, cx

loc_10118:				; CODE XREF: start+41j	start+4Cj
		pop	bx
		push	bx

loc_1011A:				; CODE XREF: start+1Fj
		inc	byte ptr [bx]
		jnz	short loc_10121
		inc	bx
		jmp	short loc_1011A
; ---------------------------------------------------------------------------

loc_10121:				; CODE XREF: start+1Cj
		mov	di, 200h
		mov	cx, di
		mov	ax, di
		rep stosb
		mov	si, di

loc_1012C:				; CODE XREF: start+34j
		lodsb
		mov	bx, ax
		inc	byte ptr [bx]
		cmp	bl, 2Eh
		jnz	short loc_1012C
		dec	byte ptr [bx]
		pop	si
		push	si
		mov	cx, bp

loc_1013C:				; CODE XREF: start+43j
		lodsb
		mov	bx, ax
		dec	byte ptr [bx]
		jl	short loc_10118
		loop	loc_1013C
		inc	dx
		pop	si
		push	si
		mov	cx, bp
		repe cmpsb
		jnz	short loc_10118
		pop	bp
		xchg	ax, dx
		aam
		call	$+3
		xchg	al, ah
		add	al, 30h
		int	29h		; DOS 2+ internal - FAST PUTCHAR
					; AL = character to display
		retn
start		endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 93h,	0, 4, 0BEh, 0C0h, 0, 56h, 31h, 0C9h, 0B4h, 0, 0CDh
		db 16h,	3Ch, 2Eh, 0AAh
seg000		ends


		end start
